version: "3.8"
name: task-2_test_2
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: 2_test_2
    networks:
        - clickhouse
    ulimits:
        nofile:
          soft: 262144
          hard: 262144
    ports:
      - "8123:8123"
    volumes:
      - vol-2_test_2:/var/lib/clickhouse
      - ./init:/docker-entrypoint-initdb.d
volumes:
  vol-2_test_2:       
networks:
  clickhouse: